keys:
  - &mara age1sz8cfaaca4eayutadj6ge7zdu4j3y055tnqaupcs26thuhxw5cpquzvc7f
  - &wakey age1jclm2wc3z9979rnqatas28zfs7dwa8v70mv26p7phl60msu4p4uqlqxwy6
  - &wakey-rpc age1k9wpg2czremlz9rxljp6c47fchlhycnkcak7wm38lkmvc49a6agqy4we4e
  - &kaiserkarel age1gn73nfnvh5kdlp32mtkse5gx8yxd8zwpxtlncvakygr389x8xq2qw34wlu

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini|bin)$
    key_groups:
    - age:
      - *mara
      - *wakey
      - *wakey-rpc
      - *kaiserkarel
  - path_regex: secrets/wakey-rpc/[^/]+\.((yaml|json|env|ini|secret))$
    key_groups:
    - age:
      - *wakey-rpc
      - *mara
  - path_regex: secrets/wakey/[^/]+\.((yaml|json|env|ini|secret))$
    key_groups:
    - age:
      - *wakey
      - *mara
  - path_regex: secrets/kaiserkarel/[^/]+\.((yaml|json|env|ini|secret))$
    key_groups:
    - age:
      - *kaiserkarel
      - *mara

